=== 3scale/porta/app/lib/three_scale/policies/schemas/manifest.schema.json
{
  "$id": "http://apicast.io/policy-v1/schema#manifest",
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "schema": {
      "$id": "#/definitions/schema",
      "$ref": "http://json-schema.org/draft-07/schema#",
      "default": {}
    },
    "version": {
      "$id": "#/definitions/version",
      "type": "string",
      "title": "The Policy Version",
      "description": "A semantic version of a policy.",
      "examples": [
        "1.3.4",
        "0.1"
      ],
      "pattern": "^((\\d+\\.)?(\\d+\\.)?(\\*|\\d+))|builtin$"
    }
  },
  "properties": {
    "name": {
      "$id": "/properties/name",
      "type": "string",
      "title": "The Policy Name",
      "description": "Name of the policy.",
      "examples": [
        "Basic Authentication"
      ],
      "minLength": 1
    },
    "summary": {
      "$id": "/properties/summary",
      "type": "string",
      "title": "The Policy Summary",
      "description": "Short description of what the policy does",
      "examples": [
        "Enables CORS (Cross Origin Resource Sharing) request handling."
      ],
      "maxLength": 75
    },
    "description": {
      "$id": "/properties/description",
      "oneOf": [
        { "type": "string",
          "minLength": 1 },
        { "type": "array", "items": { "type": "string" },
          "minItems": 1
        }
      ],
      "title": "The Policy Description",
      "description": "Longer description of what the policy does.",
      "examples": [
        "Extract authentication credentials from the HTTP Authorization header and pass them to 3scale backend.",
        [ "Redirect request to different upstream: ", " - based on path", "- set different Host header"]
      ]
    },
    "version": {
      "$ref": "#/definitions/version"
    },
    "configuration": {
      "$ref": "#/definitions/schema"
    }
  },
  "required": ["name", "version", "configuration", "summary"]
}

=== 3scale/porta/test/fixtures/policies/apicast-policy.json
{
  "$schema": "http://apicast.io/policy-v1/schema#manifest#",
  "name": "Upstream",
  "summary": "Allows to modify the upstream URL of the request based on its path.",
  "description":
    ["This policy allows to modify the upstream URL (scheme, host and port) of the request based on its path. ",
     "It accepts regular expressions and, when matched against the request path, ",
     "replaces the upstream URL with a given string. \n",
     "When combined with the APIcast policy, the upstream policy should be ",
     "placed before it in the policy chain."],
  "version": "builtin",
  "configuration": {
    "type": "object",
    "properties": {
      "rules": {
        "description": "list of rules to be applied",
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "regex": {
              "description": "regular expression to be matched",
              "type": "string"
            },
            "url": {
              "description": "new URL in case of match",
              "type": "string"
            }
          },
          "required": ["regex", "url"]
        }
      }
    }
  }
}
