=== 3scale/porta/app/lib/three_scale/swagger/schemas/swagger-1.2.schema.json
{
    "id": "http://swagger-api.github.io/schemas/v1.2/apiDeclaration.json#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "required": [ "swaggerVersion", "basePath", "apis" ],
    "properties": {
        "swaggerVersion": { "enum": [ "1.2" ] },
        "apiVersion": { "type": "string" },
        "basePath": {
            "type": "string",
            "format": "uri",
            "pattern": "^https?://"
        },
        "resourcePath": {
            "type": "string",
            "pattern": "^/"
        },
        "apis": {
            "type": "array",
            "items": { "$ref": "#/definitions/apiObject" }
        },
        "models": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/modelsObject"
            }
        },
        "produces": { "$ref": "#/definitions/mimeTypeArray" },
        "consumes": { "$ref": "#/definitions/mimeTypeArray" },
        "authorizations": { "$ref": "#/definitions/authorizationObject" }
    },
    "additionalProperties": false,
    "definitions": {
        "apiObject": {
            "type": "object",
            "required": [ "path", "operations" ],
            "properties": {
                "path": {
                    "type": "string",
                    "format": "uri-template",
                    "pattern": "^/"
                },
                "description": { "type": "string" },
                "operations": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/operationObject" }
                }
            },
            "additionalProperties": false
        },
        "mimeTypeArray": {
            "type": "array",
            "items": {
                "type": "string",
                "format": "mime-type"
            },
            "uniqueItems": true
        },
        "modelsObject": {
            "type": "object",
            "required": [ "id", "properties" ],
            "properties": {
                "id": { "type": "string" },
                "description": { "type": "string" },
                "properties": {
                    "type": "object",
                    "additionalProperties": { "$ref": "#/definitions/propertyObject" }
                },
                "subTypes": {
                    "type": "array",
                    "items": { "type": "string" },
                    "uniqueItems": true
                },
                "discriminator": { "type": "string" }
            },
            "dependencies": {
                "subTypes": [ "discriminator" ]
            }
        },
        "propertyObject": {
            "allOf": [
                {
                    "not": { "$ref": "#/definitions/modelsObject" }
                },
                {
                    "$ref": "#/definitions/dataTypeBase"
                }
            ]
        },
        "authorizationObject": {
            "type": "object",
            "additionalProperties": {
                "oneOf": [
                    {
                        "$ref": "#/definitions/basicAuth"
                    },
                    {
                        "$ref": "#/definitions/apiKey"
                    },
                    {
                        "$ref": "#/definitions/oauth2"
                    }
                ]
            }
        },
        "basicAuth": {
            "required": [ "type" ],
            "properties": {
                "type": { "enum": [ "basicAuth" ] }
            },
            "additionalProperties": false
        },
        "apiKey": {
            "required": [ "type", "passAs", "keyname" ],
            "properties": {
                "type": { "enum": [ "apiKey" ] },
                "passAs": { "enum": [ "header", "query" ] },
                "keyname": { "type": "string" }
            },
            "additionalProperties": false
        },
        "oauth2": {
            "type": "object",
            "required": [ "type", "grantTypes" ],
            "properties": {
                "type": { "enum": [ "oauth2" ] },
                "scopes": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/oauth2Scope" }
                },
                "grantTypes": {
                    "description": "NOTE: oauth2GrantType.json is missing from official schemas, accepting any object",
                    "type": "object"
                }
            },
            "additionalProperties": false
        },
        "oauth2Scope": {
            "type": "object",
            "required": [ "scope" ],
            "properties": {
                "scope": { "type": "string" },
                "description": { "type": "string" }
            },
            "additionalProperties": false
        },
        "operationObject": {
            "type": "object",
            "allOf": [
                { "$ref": "#/definitions/dataTypeBase" },
                {
                    "required": [ "method", "nickname", "parameters" ],
                    "properties": {
                        "method": { "enum": [ "GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS" ] },
                        "summary": { "type": "string", "maxLength": 120 },
                        "notes": { "type": "string" },
                        "nickname": {
                            "type": "string",
                            "pattern": "^[a-zA-Z0-9_]+$"
                        },
                        "authorizations": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/oauth2Scope"
                                }
                            }
                        },
                        "parameters": {
                            "type": "array",
                            "items": { "$ref": "#/definitions/parameterObject" }
                        },
                        "responseMessages": {
                            "type": "array",
                            "items": { "$ref": "#/definitions/responseMessageObject"}
                        },
                        "produces": { "$ref": "#/definitions/mimeTypeArray" },
                        "consumes": { "$ref": "#/definitions/mimeTypeArray" },
                        "deprecated": { "enum": [ "true", "false" ] }
                    }
                }
            ]
        },
        "responseMessageObject": {
            "type": "object",
            "required": [ "code", "message" ],
            "properties": {
                "code": { "$ref": "#/definitions/rfc2616section10" },
                "message": { "type": "string" },
                "responseModel": { "type": "string" }
            }
        },
        "rfc2616section10": {
            "type": "integer",
            "minimum": 100,
            "maximum": 600,
            "exclusiveMaximum": true
        },
        "parameterObject": {
            "type": "object",
            "allOf": [
                { "$ref": "#/definitions/dataTypeBase" },
                {
                    "required": [ "paramType", "name" ],
                    "properties": {
                        "paramType": {
                            "enum": [ "path", "query", "body", "header", "form" ]
                        },
                        "name": { "type": "string" },
                        "description": { "type": "string" },
                        "required": { "type": "boolean" },
                        "allowMultiple": { "type": "boolean" }
                    }
                },
                {
                    "description": "type File requires special paramType and consumes",
                    "oneOf": [
                        {
                            "properties": {
                                "type": { "not": { "enum": [ "File" ] } }
                            }
                        },
                        {
                            "properties": {
                                "type": { "enum": [ "File" ] },
                                "paramType": { "enum": [ "form" ] },
                                "consumes": { "enum": [ "multipart/form-data" ] }
                            }
                        }
                    ]
                }
            ]
        },
        "dataTypeBase": {
            "description": "Data type fields (section 4.3.3)",
            "type": "object",
            "oneOf": [
                { "required": [ "type" ] },
                { "required": [ "$ref" ] }
            ],
            "properties": {
                "type": { "type": "string" },
                "$ref": { "type": "string" },
                "format": { "type": "string" },
                "defaultValue": {
                    "not": { "type": [ "array", "object", "null" ] }
                },
                "enum": {
                    "type": "array",
                    "items": { "type": "string" },
                    "uniqueItems": true,
                    "minItems": 1
                },
                "minimum": { "type": "string" },
                "maximum": { "type": "string" },
                "items": { "$ref": "#/definitions/itemsObject" },
                "uniqueItems": { "type": "boolean" }
            },
            "dependencies": {
                "format": {
                    "oneOf": [
                        {
                            "properties": {
                                "type": { "enum": [ "integer" ] },
                                "format": { "enum": [ "int32", "int64" ] }
                            }
                        },
                        {
                            "properties": {
                                "type": { "enum": [ "number" ] },
                                "format": { "enum": [ "float", "double" ] }
                            }
                        },
                        {
                            "properties": {
                                "type": { "enum": [ "string" ] },
                                "format": {
                                    "enum": [ "byte", "date", "date-time" ]
                                }
                            }
                        }
                    ]
                }
            }
        },
        "itemsObject": {
            "oneOf": [
                {
                    "type": "object",
                    "required": [ "$ref" ],
                    "properties": {
                        "$ref": { "type": "string" }
                    },
                    "additionalProperties": false
                },
                {
                    "allOf": [
                        { "$ref": "#/definitions/dataTypeBase" },
                        {
                            "required": [ "type" ],
                            "properties": {
                                "type": {},
                                "format": {}
                            },
                            "additionalProperties": false
                        }
                    ]
                }
            ]
        }
    }
}

=== 3scale/porta/test/fixtures/swagger/echo-api-1.2.json
{
  "basePath": "https://echo-api.3scale.net",
  "apiVersion": "v1",
  "swaggerVersion": "1.2",
  "apis": [
    {
      "path": "/",
      "operations": [
        {
          "method": "GET",
          "summary": "Say Hello!",
          "description": "This operation says hello.",
          "nickname": "hello",
          "group": "words",
          "type": "string",
          "parameters": [
            {
              "name": "user_key",
              "description": "Your API access key",
              "type": "string",
              "paramType": "header",
              "threescale_name": "user_keys"
            }
          ]
        }
      ]
    },
    {
      "path": "/hello",
      "operations": [
        {
          "method": "GET",
          "summary": "Say Hello!",
          "description": "This operation says hello.",
          "nickname": "hello",
          "group": "words",
          "type": "string",
          "parameters": [
            {
              "name": "user_key",
              "description": "Your API access key",
              "type": "string",
              "paramType": "header",
              "threescale_name": "user_keys"
            }
          ]
        }
      ]
    }
  ]
}
